### ISSUE TITLE
pdf 预览缺少翻页按钮

### ISSUE THREAD

**Issue by chennlang** [intsig-textin/parsex-frontend#3]
![image](https://github.com/user-attachments/assets/3d7e0313-2834-40cf-8105-8b9415a940b2)
你好，我本地启动后，上传了 pdf 文件，预览页面并没有出现翻页按钮，不过我看官网截图是有的

**Comment by chennlang** [comment]
发现问题了：链接后面要加上 ?service=pdf_to_markdown

**Comment by 404error123** [comment]
该bug已修复
